package GiaoDien;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Nhanxe extends javax.swing.JFrame {

    public Nhanxe() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JLabel getLabel_loaixe() {
        return label_loaixe;
    }

    public void setLabel_loaixe(JLabel label_loaixe) {
        this.label_loaixe = label_loaixe;
    }

    public JLabel getLabel_displaybiensoxethang() {
        return label_displaybiensoxethang;
    }

    public void setLabel_displaybiensoxethang(JLabel label_displaybiensoxethang) {
        this.label_displaybiensoxethang = label_displaybiensoxethang;
    }

    public JLabel getLabel_BienSoXeVeNgay() {
        return label_BienSoXeVeNgay;
    }

    public void setLabel_BienSoXeVeNgay(JLabel label_BienSoXeVeNgay) {
        this.label_BienSoXeVeNgay = label_BienSoXeVeNgay;
    }

    public JLabel getLabel_BienSoXeVeThang() {
        return label_BienSoXeVeThang;
    }

    public void setLabel_BienSoXeVeThang(JLabel label_BienSoXeVeThang) {
        this.label_BienSoXeVeThang = label_BienSoXeVeThang;
    }

    public JLabel getLabel_IDVeNgay() {
        return label_IDVeNgay;
    }

    public void setLabel_IDVeNgay(JLabel label_IDVeNgay) {
        this.label_IDVeNgay = label_IDVeNgay;
    }

    public JLabel getLabel_IDVeThang() {
        return label_IDVeThang;
    }

    public void setLabel_IDVeThang(JLabel label_IDVeThang) {
        this.label_IDVeThang = label_IDVeThang;
    }

    public JButton getBtn_NhanXe() {
        return btn_NhanXe;
    }

    public void setBtn_NhanXe(JButton btn_NhanXe) {
        this.btn_NhanXe = btn_NhanXe;
    }

    public JComboBox<String> getCombobox_LoaiVe() {
        return combobox_LoaiVe;
    }

    public void setCombobox_LoaiVe(JComboBox<String> combobox_LoaiVe) {
        this.combobox_LoaiVe = combobox_LoaiVe;
    }

    public JComboBox<String> getCombobox_LoaiXe() {
        return combobox_LoaiXe;
    }

    public void setCombobox_LoaiXe(JComboBox<String> combobox_LoaiXe) {
        this.combobox_LoaiXe = combobox_LoaiXe;
    }

    public JComboBox<String> getCombobox_MaVe() {
        return combobox_MaVe;
    }

    public void setCombobox_MaVe(JComboBox<String> combobox_MaVe) {
        this.combobox_MaVe = combobox_MaVe;
    }

    public JTextField getTxt_BienSoXe() {
        return txt_BienSoXe;
    }

    public void setTxt_BienSoXe(JTextField txt_BienSoXe) {
        this.txt_BienSoXe = txt_BienSoXe;
    }

    public JButton getBtn_Thoat() {
        return btn_Thoat;
    }

    public void setBtn_Thoat(JButton btn_Thoat) {
        this.btn_Thoat = btn_Thoat;
    }

    public JTextField getTxt_idve() {
        return txt_idve;
    }

    public void setTxt_idve(JTextField txt_idve) {
        this.txt_idve = txt_idve;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Thoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        combobox_LoaiVe = new javax.swing.JComboBox<>();
        label_loaixe = new javax.swing.JLabel();
        combobox_LoaiXe = new javax.swing.JComboBox<>();
        label_BienSoXeVeNgay = new javax.swing.JLabel();
        txt_BienSoXe = new javax.swing.JTextField();
        label_IDVeNgay = new javax.swing.JLabel();
        btn_NhanXe = new javax.swing.JButton();
        combobox_MaVe = new javax.swing.JComboBox<>();
        txt_idve = new javax.swing.JTextField();
        label_IDVeThang = new javax.swing.JLabel();
        label_BienSoXeVeThang = new javax.swing.JLabel();
        label_displaybiensoxethang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btn_Thoat.setBackground(new java.awt.Color(0, 153, 153));
        btn_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_Thoat.setText("Quay lại");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhận xe");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Loại vé:");

        combobox_LoaiVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vé ngày", "Vé tháng" }));
        combobox_LoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_LoaiVeActionPerformed(evt);
            }
        });

        label_loaixe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_loaixe.setForeground(new java.awt.Color(255, 255, 255));
        label_loaixe.setText("Loại xe:");

        combobox_LoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy", "Oto" }));

        label_BienSoXeVeNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_BienSoXeVeNgay.setForeground(new java.awt.Color(255, 255, 255));
        label_BienSoXeVeNgay.setText("Biến số xe:");

        txt_BienSoXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BienSoXeActionPerformed(evt);
            }
        });

        label_IDVeNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_IDVeNgay.setForeground(new java.awt.Color(255, 255, 255));
        label_IDVeNgay.setText("Mã vé:");

        btn_NhanXe.setText("Nhận xe");

        combobox_MaVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        txt_idve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idveActionPerformed(evt);
            }
        });

        label_IDVeThang.setText("Mã vé:");

        label_BienSoXeVeThang.setText("Biển số xe: ");

        label_displaybiensoxethang.setText("Biển số xe vé tháng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Thoat)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_IDVeNgay)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_loaixe))
                                    .addGap(27, 27, 27))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(label_BienSoXeVeNgay)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(label_IDVeThang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_BienSoXeVeThang)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idve, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(combobox_LoaiXe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox_LoaiVe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobox_MaVe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_BienSoXe, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(btn_NhanXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displaybiensoxethang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combobox_LoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_loaixe)
                    .addComponent(combobox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_IDVeNgay)
                    .addComponent(combobox_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_IDVeThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_BienSoXeVeNgay)
                    .addComponent(txt_BienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_BienSoXeVeThang)
                    .addComponent(label_displaybiensoxethang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_NhanXe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_LoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_LoaiVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_LoaiVeActionPerformed

    private void txt_BienSoXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BienSoXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BienSoXeActionPerformed

    private void txt_idveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idveActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NhanXe;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JComboBox<String> combobox_LoaiVe;
    private javax.swing.JComboBox<String> combobox_LoaiXe;
    private javax.swing.JComboBox<String> combobox_MaVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_BienSoXeVeNgay;
    private javax.swing.JLabel label_BienSoXeVeThang;
    private javax.swing.JLabel label_IDVeNgay;
    private javax.swing.JLabel label_IDVeThang;
    private javax.swing.JLabel label_displaybiensoxethang;
    private javax.swing.JLabel label_loaixe;
    private javax.swing.JTextField txt_BienSoXe;
    private javax.swing.JTextField txt_idve;
    // End of variables declaration//GEN-END:variables
}
